# 数据集
data_dir: "./data"   # 数据目录
train_data_path: "${data_dir}/dataset/clue/train.jsonl"
dev_data_path: "${data_dir}/dataset/clue/dev.jsonl"
test_data_path: "${data_dir}/dataset/clue/test.jsonl"
label_data_path: "${data_dir}/dataset/clue/label.json"
num_labels: 31

# 模型设置
model_name: "BertCrf"
model_path: "${data_dir}/experiment/bert_crf.pth"
device: "cuda:0"
pretrain_path: "${data_dir}/pretrain/bert-base-chinese"
batch_size: 64
dropout: 0.3
epoch_num: 50
learning_rate: 3e-5

defaults:
  # - dataset: clue
  # - model: bert_crf
  # 修改hydra默认值
  - _self_
  - override hydra/job_logging: custom
