data_dir: "./data"

logger:
  path: "${data_dir}/log"

datasets:
  train_data_path: "${data_dir}/dataset/train.jsonl"
  dev_data_path: "${data_dir}/dataset/dev.jsonl"
  test_data_path: "${data_dir}/dataset/test.jsonl"

entity_labels:
  label_data_path: "${data_dir}/dataset/label.json"

model:
  pretrained_model_dir:
    win32: "E:/data/models"
    default: "/data/models"
  bert_base_chinese: "${model.pretrained_model_dir.default}/bert-base-chinese"
  model_path: "${data_dir}/experiment/ner.pth"

directories:
  - dataset
  - experiment
  - log
  - pretrained