# 数据集
data_dir: "./data"   # 数据目录
train_data_path: "${data_dir}/dataset/clue/train.jsonl"
dev_data_path: "${data_dir}/dataset/clue/dev.jsonl"
test_data_path: "${data_dir}/dataset/clue/test.jsonl"
label_data_path: "${data_dir}/dataset/clue/label.json"

# 模型设置
model_name: "BertBiLstmCrf"
model_path: "${data_dir}/outputs/${model_name}.pth"
device: "cuda:0"
batch_size: 64
dropout: 0.3
epoch_num: 50
learning_rate: 3e-5
pretrain_path: "../model_hub/bert-base-chinese"
num_labels: 31
lstm_num_layers: 1
lstm_hidden_size: 128

defaults:
  - _self_
  - override hydra/job_logging: custom

hydra:
  run:
    dir: ${data_dir}/experiment/${hydra.job.name}/${now:%Y-%m-%d}